namespace SuperNodes.Example;

using System;
using Godot;
using SharedPowerUps;

[SuperNode(typeof(MyPowerUp<Node2D, Godot.Object>), "LifecycleMethodA", typeof(SharedPowerUp))]
public partial class MyNode : Node {
  public string ScriptProperty { get; set; } = "hello";

  public override partial void _Notification(long what);

  public void OnReady() { }

  public void OnProcess(double _) { }
}

/// <summary>
/// Pretend this is partial class is generated by another generator.
/// </summary>
public partial class MyNode {
  public void LifecycleMethodA(long what) { }
}

public class SomeObject { }

public interface IMyPowerUpGeneric<TSomethingA, TSomethingB> { }
public interface IMyPowerUp { }

[PowerUp]
public abstract partial class MyPowerUp<TA, TB> : Node, IMyPowerUp, IMyPowerUpGeneric<string, bool> {
  public static int MyNumber { get; set; } = 42;

  private readonly struct MyTypeReceiver : ITypeReceiver<bool> {
    public Node Node { get; }

    public MyTypeReceiver(Node node) {
      Node = node;
    }

    public bool Receive<T>() => Node is IEquatable<T> or TA or TB;
  }

  public string AddedProperty { get; set; } = "";

  public void OnMyPowerUp(long what) {
    MyPowerUp<TA, TB>.MyNumber = 10;
    if (what == Node.NotificationReady) {
      var receiver = new MyTypeReceiver(this);
      GD.Print(
        "is IEquatable<string>? " +
        GetScriptPropertyOrFieldType("AddedProperty", receiver)
      );
    }
  }

  // Stubs for the generated static reflection tables generated on SuperNodes

#pragma warning disable RCS1158

  internal static ScriptPropertyOrField[] PropertiesAndFields { get; }
    = default!;
  internal static TResult GetScriptPropertyOrFieldType<TResult>(
    string scriptProperty, ITypeReceiver<TResult> receiver
  ) => default!;

#pragma warning restore RCS1158
}
