namespace GeneralExample;

using Godot;
using SuperNodes.Types;

[SuperNode(typeof(ExamplePowerUp<int>), "OtherGenerator")]
public partial class ExampleSuperNode : Node {
  public override partial void _Notification(int what);

  public void OnReady() { }
}

[PowerUp]
public partial class ExamplePowerUp<T> : Node, IExamplePowerUp<T> {
  T IExamplePowerUp<T>.TestValue { get; } = default!;
}

public interface IExamplePowerUp<T> {
  T TestValue { get; }
}

// Pretend this implementation is generated by another generator.
public partial class ExampleSuperNode {
  public void OtherGenerator(int what) { }
}
